{{- if and .Values.secret.create .Values.secret.key -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "certkit-agent.fullname" . }}-secrets
  labels:
    {{- include "certkit-agent.labels" . | nindent 4 }}
type: Opaque
data:
  registration-key: {{ .Values.secret.key | b64enc | quote }}
{{- end }}
